spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=bookitDB


jwt.secret-key=bXlTdXBlclNlY3VyZUtleVRoYXRJc0xvbmdFbm91Z2gxMjMh
jwt.expiration-time=3600000


anthropic.api.url=https://api.anthropic.com/v1/messages
anthropic.api.key=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

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
