export enum RoomType {
    SINGLE = "SINGLE",
    DOUBLE = "DOUBLE",
    TWIN = "TWIN",
    TRIPLE = "TRIPLE",
    QUAD = "QUAD",
    FAMILY_SUITE = "FAMILY_SUITE",
    KING = "KING",
    QUEEN = "QUEEN",
    SUITE = "SUITE",
    JUNIOR_SUITE = "JUNIOR_SUITE",
    PENTHOUSE = "PENTHOUSE",
    ACCESSIBLE = "ACCESSIBLE",
    BUNK = "BUNK",
    HONEYMOON_SUITE = "HONEYMOON_SUITE",
    DOUBLE_SEA_VIEW = "DOUBLE_SEA_VIEW",
    BEACHFRONT = "BEACHFRONT",
    GARDEN_VIEW = "GARDEN_VIEW",
    POOLSIDE = "POOLSIDE",
    SUPERIOR = "SUPERIOR",
    DELUXE = "DELUXE",
    BUSINESS = "BUSINESS"
  }
  